/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findAll"];
        put: operations["update"];
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["disable"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findAll_1"];
        put: operations["update_1"];
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findAll_2"];
        put: operations["update_2"];
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/privileges/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_3"];
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findAll_3"];
        put: operations["update_4"];
        post: operations["create_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/org/parameters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listOrgEditableParameters"];
        put: operations["upsertOrgParameter"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findAll_4"];
        put: operations["update_5"];
        post: operations["create_4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/stages/{stageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateStage"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/job-card": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["saveJobCard"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/parameters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listParameters"];
        put: operations["upsertParameter"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/privileges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCatalog"];
        put?: never;
        post: operations["create_5"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/stages/{stageId}/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["scanStage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mfa/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyMfa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mfa/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["setupMfa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mfa/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["enableMfa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mfa/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["disableMfa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/authenticate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["authenticate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findById_1"];
        put?: never;
        post?: never;
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quotes/{quoteNumber}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findByQuoteNumber"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quotes/{quoteNumber}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findById_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findById_3"];
        put?: never;
        post?: never;
        delete: operations["cancel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/stages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["stages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["audit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["counts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/validate-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["validateToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/refresh-cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["refreshCache"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/parameters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteParameter"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UpdateUserRequest: {
            /** Format: int64 */
            id: number;
            displayName: string;
            mobileNumber?: string;
            enabled?: boolean;
            roleIds: number[];
            password?: string;
        };
        OrganizationDTO: {
            /** Format: int64 */
            id: number;
            companyName?: string;
            companyCode?: string;
            address?: string;
            city?: string;
            country?: string;
            postalCode?: string;
            phone?: string;
            mobileNumber?: string;
            email?: string;
            gstNo?: string;
        };
        UserDTO: {
            /** Format: int64 */
            id?: number;
            username?: string;
            displayName?: string;
            email?: string;
            mobileNumber?: string;
            locale?: string;
            designation?: string;
            authProvider?: string;
            organization?: components["schemas"]["OrganizationDTO"];
            rolesPrivileges?: string[];
            roleIds?: number[];
            roleCodes?: string[];
            enabled?: boolean;
            totpEnabled?: boolean;
            mfaAvailable?: boolean;
        };
        RoleDTO: {
            /** Format: int64 */
            id: number;
            role: string;
            roleCode: string;
            privilegeCodes: string[];
        };
        QuotationDTO: {
            /** Format: int64 */
            id: number;
            quoteNumber: string;
            company?: string;
            title?: string;
            /** @enum {string} */
            status?: "AWAITING_ACCEPTANCE" | "ACCEPTED" | "DECLINED" | "EXPIRED" | "COMPLETED";
            /** @enum {string} */
            lastEvent?: string;
            factoryStatus?: string;
            quoteUrl?: string;
            /** Format: int64 */
            customerId?: number;
            fromDetails?: {
                [key: string]: Record<string, never>;
            };
            quoteFor?: {
                [key: string]: Record<string, never>;
            };
            selectedItems?: {
                [key: string]: Record<string, never>;
            }[];
            /** Raw source payload; sent only on the single-quote endpoint. */
            payload?: {
                [key: string]: Record<string, never>;
            };
            events?: components["schemas"]["QuotientEventDTO"][];
        };
        QuotientEventDTO: {
            /** Format: int64 */
            id?: number;
            quoteNumber?: string;
            /** @enum {string} */
            entityType?: "QUOTE" | "CUSTOMER" | "PAYMENT";
            eventCode?: string;
            externalId?: string;
            payload?: {
                [key: string]: Record<string, never>;
            };
            processed?: boolean;
            processError?: string;
            /** Format: date-time */
            occurredAt?: string;
        };
        PrivilegeDTO: {
            /** Format: int64 */
            id: number;
            privilege: string;
            privilegeCode: string;
            /** @enum {string} */
            privilegeType: "MENU" | "ACTION" | "FIELD";
            domain?: string;
            fieldKey?: string;
            /** @enum {string} */
            accessMode?: "READ" | "WRITE";
            /** Format: int64 */
            parentId?: number;
            /** Format: int32 */
            sortOrder?: number;
            platformOnly?: boolean;
            systemManaged?: boolean;
            active?: boolean;
        };
        ApplicationParameterDTO: {
            /** Format: int64 */
            id?: number;
            paramName: string;
            paramValue?: string;
            paramType?: string;
            description?: string;
            /** Format: int64 */
            organizationId?: number;
            orgEditable?: boolean;
            readonly inherited?: boolean;
        };
        CustomerContactDTO: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            customerId: number;
            companyId?: string;
            name: string;
            address?: string;
            phone?: string;
            email?: string;
            details?: {
                [key: string]: Record<string, never>;
            };
        };
        CustomerDTO: {
            /** Format: int64 */
            id?: number;
            companyId?: string;
            companyName: string;
            address?: string;
            phone?: string;
            email?: string;
            details?: {
                [key: string]: Record<string, never>;
            };
        };
        GroupChatDTO: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            jobId?: number;
            body: string;
            /** @enum {string} */
            tag?: "QUESTION" | "BLOCKER" | "UPDATE" | "HANDOVER";
            received?: boolean;
            readBy?: string;
            /** Format: int64 */
            sentBy?: number;
            /** Format: date-time */
            sentAt?: string;
        };
        JobDTO: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            version: number;
            jobNumber?: string;
            quoteNumber?: string;
            /** @enum {string} */
            readonly origin?: "QUOTE" | "FACTORY";
            /** Format: int64 */
            customerId?: number;
            customerCompanyName?: string;
            customerContactName?: string;
            customerContactEmail?: string;
            customerContactPhone?: string;
            title?: string;
            /** Format: date */
            dueDate?: string;
            /** @enum {string} */
            readonly stageStatus?: "PENDING" | "AWAITING_MANAGER_APPROVAL" | "READY_TO_MANUFACTURE" | "IN_FABRICATION" | "ON_HOLD" | "COMPLETE" | "CANCELLED";
            /** @enum {string} */
            priority?: "NORMAL" | "HIGH" | "RUSH";
            stageStatusLabel?: string;
            resinCode?: string;
            /** Format: int64 */
            assignedUserId?: number;
            estimatedHours?: number;
            alert?: string;
            readonly jobCard?: {
                [key: string]: Record<string, never>;
            };
            /** Format: int64 */
            readonly currentStageId?: number;
            readonly currentStageKey?: string;
            /** Format: int32 */
            readonly percentComplete?: number;
            /** Format: date-time */
            readonly createdDate?: string;
            readonly stages?: components["schemas"]["JobStageDTO"][];
            readonly documents?: components["schemas"]["JobDocumentDTO"][];
            readonly payments?: components["schemas"]["JobPaymentDTO"][];
            readonly messages?: components["schemas"]["GroupChatDTO"][];
            readonly customer?: components["schemas"]["CustomerDTO"];
            readonly customerContacts?: components["schemas"]["CustomerContactDTO"][];
            readonly quotation?: components["schemas"]["QuotationDTO"];
        };
        JobDocumentDTO: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            jobId?: number;
            /** Format: int64 */
            jobStageId?: number;
            documentName?: string;
            /** @enum {string} */
            documentType?: "DRAWING" | "PHOTO" | "CERTIFICATE" | "DELIVERY_DOCKET" | "JOB_CARD_PDF" | "COI" | "OTHER";
            mimeType?: string;
            /** Format: int64 */
            sizeBytes?: number;
            remarks?: string;
            /** Format: int32 */
            documentVersion?: number;
            /** Format: int64 */
            uploadedBy?: number;
            /** Format: date-time */
            uploadedAt?: string;
        };
        JobPaymentDTO: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            jobId?: number;
            quoteNumber?: string;
            amount: number;
            currency?: string;
            /** @enum {string} */
            kind: "DEPOSIT" | "PROGRESS" | "FINAL";
            /** @enum {string} */
            status?: "DUE" | "RECEIVED" | "OVERDUE" | "WRITTEN_OFF";
            /** @enum {string} */
            paymentMode?: "CASH" | "ACCOUNT";
            /** Format: date */
            dueDate?: string;
            /** Format: date-time */
            receivedAt?: string;
            reference?: string;
            /** Format: int64 */
            recordedBy?: number;
        };
        JobStageDTO: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            parentId?: number;
            stageKey?: string;
            stageName?: string;
            /** @enum {string} */
            stageType?: "MILESTONE" | "OPERATION";
            /** @enum {string} */
            status?: "PENDING" | "IN_PROGRESS" | "COMPLETE" | "SKIPPED" | "BLOCKED";
            /** Format: int32 */
            sortOrder?: number;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            completedAt?: string;
            notes?: string;
            /** Format: int64 */
            dependsOnStageId?: number;
            assignedTeam?: string;
            /** Format: int32 */
            percentComplete?: number;
            children?: components["schemas"]["JobStageDTO"][];
        };
        JobStageUpdateRequest: {
            /** @enum {string} */
            status?: "PENDING" | "IN_PROGRESS" | "COMPLETE" | "SKIPPED" | "BLOCKED";
            /** Format: int32 */
            percentComplete?: number;
            notes?: string;
            assignedTeam?: string;
        };
        CreateUserRequest: {
            email: string;
            password: string;
            displayName: string;
            mobileNumber?: string;
            roleIds: number[];
        };
        CreateOrganizationRequest: {
            companyName: string;
            companyCode: string;
            address?: string;
            city?: string;
            country?: string;
            postalCode?: string;
            phone?: string;
            mobileNumber?: string;
            email?: string;
            gstNo?: string;
            adminPassword: string;
            adminEmail: string;
            adminDisplayName: string;
            adminMobileNumber?: string;
        };
        OrganizationProvisionResponse: {
            organization?: components["schemas"]["OrganizationDTO"];
            adminUsername?: string;
        };
        RefreshTokenRequest: {
            refreshToken: string;
        };
        AuthenticationResponse: {
            token?: string;
            refreshToken?: string;
            /** Format: int64 */
            expiresIn?: number;
            requires2fa?: boolean;
            mfaToken?: string;
        };
        MfaVerifyRequest: {
            mfaToken: string;
            code: string;
        };
        MfaSetupResponse: {
            secret?: string;
            otpAuthUri?: string;
            qrCodeDataUri?: string;
        };
        MfaCodeRequest: {
            code: string;
        };
        MfaDisableRequest: {
            password: string;
            code: string;
        };
        AuthenticationRequest: {
            email: string;
            password: string;
        };
        PageResponseUserDTO: {
            content?: components["schemas"]["UserDTO"][];
            /** Format: int32 */
            number?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
        };
        PageResponseRoleDTO: {
            content?: components["schemas"]["RoleDTO"][];
            /** Format: int32 */
            number?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
        };
        PageResponseQuotationDTO: {
            content?: components["schemas"]["QuotationDTO"][];
            /** Format: int32 */
            number?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
        };
        PageResponseOrganizationDTO: {
            content?: components["schemas"]["OrganizationDTO"][];
            /** Format: int32 */
            number?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
        };
        JobSummaryDTO: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            version?: number;
            jobNumber?: string;
            quoteNumber?: string;
            /** @enum {string} */
            origin?: "QUOTE" | "FACTORY";
            title?: string;
            customerCompanyName?: string;
            /** Format: date */
            dueDate?: string;
            /** @enum {string} */
            stageStatus?: "PENDING" | "AWAITING_MANAGER_APPROVAL" | "READY_TO_MANUFACTURE" | "IN_FABRICATION" | "ON_HOLD" | "COMPLETE" | "CANCELLED";
            /** @enum {string} */
            priority?: "NORMAL" | "HIGH" | "RUSH";
            resinCode?: string;
            /** Format: int64 */
            assignedUserId?: number;
            currentStageKey?: string;
            /** Format: int32 */
            percentComplete?: number;
            /** Format: date-time */
            createdDate?: string;
        };
        PageResponseJobSummaryDTO: {
            content?: components["schemas"]["JobSummaryDTO"][];
            /** Format: int32 */
            number?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
        };
        JobAuditHistoryDTO: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            jobId?: number;
            /** @enum {string} */
            eventCode?: "JOB_CREATED" | "STATUS_CHANGED" | "JOB_CARD_SAVED" | "JOB_CARD_DOWNLOADED" | "STAGE_COMPLETED" | "WORKER_ASSIGNED" | "PAYMENT_RECORDED" | "DOCUMENT_UPLOADED" | "JOB_CANCELLED";
            statusFrom?: string;
            statusTo?: string;
            actor?: string;
            actorRole?: string;
            detail?: {
                [key: string]: Record<string, never>;
            };
            /** Format: date-time */
            occurredAt?: string;
        };
        PageResponseJobAuditHistoryDTO: {
            content?: components["schemas"]["JobAuditHistoryDTO"][];
            /** Format: int32 */
            number?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
        };
        JobCountsDTO: {
            /** Format: int64 */
            total?: number;
            /** Format: int64 */
            active?: number;
            /** Format: int64 */
            overdue?: number;
            /** Format: int64 */
            notStarted?: number;
            /** Format: int64 */
            awaitingApproval?: number;
            /** Format: int64 */
            ready?: number;
            /** Format: int64 */
            manufacturing?: number;
            /** Format: int64 */
            onHold?: number;
            /** Format: int64 */
            delivered?: number;
            /** Format: int64 */
            cancelled?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    findAll: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseUserDTO"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserDTO"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserDTO"];
                };
            };
        };
    };
    disable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserDTO"];
                };
            };
        };
    };
    findAll_1: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseRoleDTO"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    findAll_2: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseQuotationDTO"];
                };
            };
        };
    };
    update_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuotationDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QuotationDTO"];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuotationDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QuotationDTO"];
                };
            };
        };
    };
    update_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrivilegeDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PrivilegeDTO"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    findAll_3: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseOrganizationDTO"];
                };
            };
        };
    };
    update_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    create_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrganizationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrganizationProvisionResponse"];
                };
            };
        };
    };
    listOrgEditableParameters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApplicationParameterDTO"][];
                };
            };
        };
    };
    upsertOrgParameter: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationParameterDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApplicationParameterDTO"];
                };
            };
        };
    };
    findAll_4: {
        parameters: {
            query?: {
                status?: "PENDING" | "AWAITING_MANAGER_APPROVAL" | "READY_TO_MANUFACTURE" | "IN_FABRICATION" | "ON_HOLD" | "COMPLETE" | "CANCELLED";
                priority?: "NORMAL" | "HIGH" | "RUSH";
                assignedTo?: number;
                dueBefore?: string;
                search?: string;
                sort?: "DUE_DATE" | "RECENT" | "OLDEST";
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseJobSummaryDTO"];
                };
            };
        };
    };
    update_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["JobDTO"];
                };
            };
        };
    };
    create_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["JobDTO"];
                };
            };
        };
    };
    updateStage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                stageId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobStageUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["JobStageDTO"];
                };
            };
        };
    };
    saveJobCard: {
        parameters: {
            query: {
                version: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: Record<string, never>;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["JobDTO"];
                };
            };
        };
    };
    listParameters: {
        parameters: {
            query?: {
                organizationId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApplicationParameterDTO"][];
                };
            };
        };
    };
    upsertParameter: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationParameterDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApplicationParameterDTO"];
                };
            };
        };
    };
    listCatalog: {
        parameters: {
            query?: {
                type?: "MENU" | "ACTION" | "FIELD";
                domain?: string;
                active?: boolean;
                grouped?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    create_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrivilegeDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PrivilegeDTO"];
                };
            };
        };
    };
    scanStage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                stageId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["JobStageDTO"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthenticationResponse"];
                };
            };
        };
    };
    verifyMfa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaVerifyRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthenticationResponse"];
                };
            };
        };
    };
    setupMfa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MfaSetupResponse"];
                };
            };
        };
    };
    enableMfa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaCodeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    disableMfa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaDisableRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    authenticate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthenticationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthenticationResponse"];
                };
            };
        };
    };
    findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserDTO"];
                };
            };
        };
    };
    findById_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoleDTO"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoleDTO"];
                };
            };
        };
    };
    findByQuoteNumber: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quoteNumber: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QuotationDTO"];
                };
            };
        };
    };
    events: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quoteNumber: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QuotientEventDTO"][];
                };
            };
        };
    };
    findById_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrganizationDTO"];
                };
            };
        };
    };
    findById_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["JobDTO"];
                };
            };
        };
    };
    cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    stages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["JobStageDTO"][];
                };
            };
        };
    };
    audit: {
        parameters: {
            query?: {
                since?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseJobAuditHistoryDTO"];
                };
            };
        };
    };
    counts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["JobCountsDTO"];
                };
            };
        };
    };
    validateToken: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": boolean;
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserDTO"];
                };
            };
        };
    };
    refreshCache: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    deleteParameter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
}
