/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/authenticate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in with email and password
         * @description Returns tokens directly, or an MFA challenge when the organization has
         *     `MFA_TOTP_ENABLED` **and** the user has enrolled TOTP. Both conditions
         *     must hold — org-level alone does not force a challenge.
         */
        post: operations["authenticate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mfa/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete an MFA challenge
         * @description Exchanges the short-lived `mfaToken` (5 min TTL) plus a 6-digit code for tokens.
         */
        post: operations["verifyMfa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate the session */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke a refresh token */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The signed-in user, with resolved privileges
         * @description The frontend's authority for role and privilege resolution. `organization`
         *     is null for the platform Super Admin.
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update your own profile
         * @description **Not yet implemented — required by DEL-01 (profile settings screen).**
         *
         *     Self-service editing of your own display name and mobile number. Needed
         *     because `PUT /users` is gated behind `USER_UPDATE`, which a plain org
         *     user does not hold — today they cannot edit their own profile at all.
         *
         *     Must NOT accept `roleIds`, `enabled`, `email`, or `password`. Role
         *     changes go through `PUT /users`; password changes need a separate
         *     endpoint carrying the current password.
         */
        patch: operations["updateMyProfile"];
        trace?: never;
    };
    "/auth/mfa/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Begin TOTP enrolment */
        post: operations["setupMfa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mfa/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm and activate TOTP */
        post: operations["enableMfa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mfa/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Disable TOTP
         * @description Requires the account password and a current authenticator code.
         */
        post: operations["disableMfa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users in the caller's organization */
        get: operations["listUsers"];
        /** Update a user */
        put: operations["updateUser"];
        /** Create a user */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a user */
        get: operations["getUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Disable a user */
        put: operations["disableUser"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List roles */
        get: operations["listRoles"];
        /** Update a role */
        put: operations["updateRole"];
        /** Create a role */
        post: operations["createRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/privileges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the privilege catalog
         * @description ACTION privileges are synced from backend annotations on startup and are
         *     read-only. MENU and FIELD entries are managed through this API and are
         *     **not** enforced server-side in v1 — MENU drives UX only, FIELD is not a
         *     field-level ACL. Do not rely on either as a security boundary.
         */
        get: operations["listPrivileges"];
        put?: never;
        /** Create a MENU or FIELD privilege */
        post: operations["createPrivilege"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List organizations */
        get: operations["listOrganizations"];
        put?: never;
        /**
         * Provision an organization
         * @description Single transaction: creates the org, an ORG_ADMIN role holding every
         *     non-platform ACTION privilege, and the first admin user.
         */
        post: operations["createOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/parameters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List global parameters */
        get: operations["listGlobalParameters"];
        put?: never;
        /** Create or update a global parameter */
        post: operations["upsertGlobalParameter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/org/parameters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List parameters for the caller's organization
         * @description Resolution is global → org override. `inherited: true` marks a value
         *     coming from the global default rather than an org-specific row.
         *
         *     Carries the SharePoint and Quotient connection settings that DEL-01
         *     requires to be admin-configurable rather than hardcoded.
         */
        get: operations["listOrgParameters"];
        put?: never;
        /** Set an org-level parameter override */
        post: operations["upsertOrgParameter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List jobs
         * @description DEL-01 job list. Supports multi-attribute filtering and free-text search
         *     across job number, name, PO number, and customer.
         */
        get: operations["listJobs"];
        put?: never;
        /**
         * Create a job manually
         * @description Manual creation wizard (DEL-01). Quotient-derived jobs are created by the
         *     webhook processor, not here.
         *
         *     Conditional flag rules the backend must enforce — the frontend enforces
         *     them too, but the API is the boundary that matters:
         *     - `needsJobCard: false` (delivery-docket-only) cannot be created in a
         *       manufacturing status.
         *     - `qaCompleted: true` is invalid while `needsJobCard: true`.
         */
        post: operations["createJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobNumber}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Public job number, e.g. `JOB-1001` or `JOB-Q-4821`. */
                jobNumber: components["parameters"]["JobNumberPath"];
            };
            cookie?: never;
        };
        /**
         * Single Job View
         * @description Full job metadata including linked POs, SharePoint state, and flags.
         */
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Partial job update
         * @description Only supplied fields are applied. `auditAction` and `auditDetail` are
         *     recorded against the change so the job audit trail attributes it.
         *
         *     Status transitions are validated against the state machine; an illegal
         *     transition is a 400, not a silent no-op.
         */
        patch: operations["updateJob"];
        trace?: never;
    };
    "/jobs/{jobNumber}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job audit trail */
        get: operations["listJobAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/dashboard/kpis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * KPI dashboard counts
         * @description Live job counts grouped by status and stage group (DEL-01).
         */
        get: operations["getJobKpis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List customers */
        get: operations["listCustomers"];
        put?: never;
        /** Create a customer */
        post: operations["createCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** Customer profile with job history */
        get: operations["getCustomer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a customer */
        patch: operations["updateCustomer"];
        trace?: never;
    };
    "/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Quotient quotes */
        get: operations["listQuotes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quotes/{quoteNumber}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quote detail with line items, questions, and event timeline */
        get: operations["getQuote"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/quotient": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Quotient webhook ingestion
         * @description **DEL-02.** Quotient permanently pauses a webhook after 3 consecutive
         *     non-2xx responses or timeouts, so this endpoint must archive the raw
         *     payload and return 200 immediately. All parsing happens asynchronously
         *     on the JobRunr queue.
         *
         *     Requirements:
         *     - Validate the shared secret before doing anything else. Reject with 401
         *       on mismatch. **The current Next.js implementation has this check
         *       commented out — it must not be carried across.**
         *     - Persist the entire raw payload verbatim for replay and audit.
         *     - Take a transactional lock on `quotientQuoteId` so duplicate deliveries
         *       never produce duplicate jobs.
         *     - Return 200 even when downstream processing fails; failures are
         *       retried from the queue, never surfaced to Quotient.
         */
        post: operations["ingestQuotientWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobNumber}/purchase-orders": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Public job number, e.g. `JOB-1001` or `JOB-Q-4821`. */
                jobNumber: components["parameters"]["JobNumberPath"];
            };
            cookie?: never;
        };
        /** POs linked to a job, newest version first */
        get: operations["listJobPurchaseOrders"];
        put?: never;
        /**
         * Link a PO to a job
         * @description **DEL-03.** Creates v1, or the next version when `poNumber` already
         *     exists on the job. Versions are immutable once created — an amendment is
         *     a new version, never an edit.
         *
         *     On creation the variance engine compares the PO against the accepted
         *     quote and attaches a field-level report.
         */
        post: operations["createPurchaseOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/purchase-orders/{id}/variance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Field-level variance report against the accepted quote
         * @description Drives the red-flagged discrepancy UI. Every differing field is returned
         *     with both values so the frontend renders the comparison without
         *     re-deriving anything.
         */
        get: operations["getPurchaseOrderVariance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/purchase-orders/{id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign off on a variance report
         * @description Records human review of flagged discrepancies (DEL-03).
         */
        post: operations["acknowledgePurchaseOrderVariance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobNumber}/sharepoint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * SharePoint sync state and file tree for a job
         * @description **DEL-04.** `syncStatus` drives the Single Job View indicator. Return
         *     `NOT_CONFIGURED` when the org has no SharePoint credentials rather than
         *     an error — the panel renders an empty state, not a failure.
         */
        get: operations["getJobSharePointState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobNumber}/sharepoint/provision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Provision the job folder hierarchy
         * @description Creates `[jobName]-[jobNumber]/` with `/Drawings`, `/Photos`, and `/POs`.
         *     Sanitizes special characters and truncates long paths safely. Idempotent
         *     — re-provisioning an existing folder returns the existing state.
         */
        post: operations["provisionJobSharePointFolder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobNumber}/sharepoint/upload-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open a chunked upload session
         * @description For CAD and SmartCut files over 4 MB. Returns a Graph upload URL the
         *     browser streams chunks to directly, so large files never transit the
         *     VPS. The backend retries with backoff on Graph-side failures.
         */
        post: operations["createSharePointUploadSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description The only error shape. Fields are omitted when empty, so treat every
         *     property as optional.
         */
        ExceptionResponse: {
            businessErrorCode?: number;
            businessErrorDescription?: string;
            error?: string;
            validationErrors?: string[];
            /** @description Field name → message. */
            errors?: {
                [key: string]: string;
            };
        };
        SuccessResponse: {
            /** @example 202 */
            statusCode?: number;
            /** @example Request accepted successfully */
            message?: string;
        };
        /** @description Base envelope. Concrete types narrow `content`. */
        PageResponse: {
            /** @description 0-based page index. */
            number?: number;
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            totalPages?: number;
            first?: boolean;
            last?: boolean;
        };
        AuthenticationRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        /**
         * @description Either a token pair or an MFA challenge. When `requires2fa` is true,
         *     `token` and `refreshToken` are absent and `mfaToken` is present.
         */
        AuthenticationResponse: {
            token?: string;
            refreshToken?: string;
            /**
             * Format: int64
             * @description Access token lifetime in ms.
             */
            expiresIn?: number;
            requires2fa?: boolean;
            /** @description Short-lived challenge token, 5 min TTL. */
            mfaToken?: string;
        };
        RefreshTokenRequest: {
            refreshToken: string;
        };
        MfaVerifyRequest: {
            mfaToken: string;
            code: string;
        };
        MfaCodeRequest: {
            code: string;
        };
        MfaDisableRequest: {
            /** Format: password */
            password: string;
            code: string;
        };
        MfaSetupResponse: {
            /** @description Manual entry key. */
            secret?: string;
            otpAuthUri?: string;
            /** @description data:image/png;base64,… */
            qrCodeDataUri?: string;
        };
        UserDTO: {
            /** Format: int64 */
            id?: number;
            username?: string;
            displayName?: string;
            /** Format: email */
            email?: string;
            mobileNumber?: string;
            locale?: string;
            designation?: string;
            /** @enum {string} */
            authProvider?: "LOCAL" | "GOOGLE" | "MICROSOFT";
            /** @description Null for the platform Super Admin. */
            organization?: components["schemas"]["OrganizationDTO"] | null;
            /** @description Flattened ACTION privilege codes. The frontend's authorization source. */
            rolesPrivileges?: string[];
            roleIds?: number[];
            roleCodes?: string[];
            enabled?: boolean;
            totpEnabled?: boolean;
            /** @description Org-level MFA_TOTP_ENABLED. */
            mfaAvailable?: boolean;
        };
        CreateUserRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
            displayName: string;
            mobileNumber?: string;
            roleIds: number[];
        };
        UpdateUserRequest: {
            /** Format: int64 */
            id: number;
            displayName: string;
            mobileNumber?: string;
            enabled?: boolean;
            roleIds: number[];
            /**
             * Format: password
             * @description Omit to leave unchanged.
             */
            password?: string;
        };
        /**
         * @description Deliberately narrow. Adding `roleIds` or `enabled` here would let any
         *     user escalate their own access.
         */
        UpdateMyProfileRequest: {
            displayName: string;
            mobileNumber?: string;
            locale?: string;
        };
        OrganizationDTO: {
            /** Format: int64 */
            id?: number;
            companyName?: string;
            companyCode?: string;
            address?: string;
            city?: string;
            country?: string;
            postalCode?: string;
            phone?: string;
            mobileNumber?: string;
            /** Format: email */
            email?: string;
            gstNo?: string;
        };
        CreateOrganizationRequest: {
            companyName: string;
            companyCode: string;
            address?: string;
            city?: string;
            country?: string;
            postalCode?: string;
            phone?: string;
            mobileNumber?: string;
            /** Format: email */
            email?: string;
            gstNo?: string;
            /** Format: email */
            adminEmail: string;
            /** Format: password */
            adminPassword: string;
            adminDisplayName: string;
            adminMobileNumber?: string;
        };
        OrganizationProvisionResponse: {
            organization?: components["schemas"]["OrganizationDTO"];
            /** @description Login identity (email) for the provisioned admin. */
            adminUsername?: string;
        };
        RoleDTO: {
            /** Format: int64 */
            id?: number;
            role: string;
            /** @description Unique per organization. */
            roleCode: string;
            privilegeCodes: string[];
        };
        PrivilegeDTO: {
            /** Format: int64 */
            id?: number;
            privilege?: string;
            privilegeCode: string;
            /** @enum {string} */
            privilegeType?: "ACTION" | "MENU" | "FIELD";
            domain?: string;
            fieldKey?: string;
            /** @enum {string} */
            accessMode?: "READ" | "WRITE";
            parentId?: number | null;
            sortOrder?: number;
            platformOnly?: boolean;
            /** @description Annotation-synced. Read-only. */
            systemManaged?: boolean;
            active?: boolean;
        };
        ApplicationParameterDTO: {
            /** Format: int64 */
            id?: number;
            paramName: string;
            paramValue?: string;
            /** @enum {string} */
            paramType?: "String" | "Boolean" | "Number" | "Json";
            description?: string;
            /** @description Null means the global default. */
            organizationId?: number | null;
            orgEditable?: boolean;
            /** @description True when the value comes from the global default. */
            inherited?: boolean;
        };
        /**
         * @description Lifecycle from the PRD notification matrix, plus two exception states.
         *
         *     `On Hold` and `Cancelled` are not in the PRD matrix but are required —
         *     the Quotient `quote_declined` handler transitions jobs to Cancelled.
         *     Neither dispatches a client email.
         *
         *     **Open question for the backend team:** the tech spec lists 15 lifecycle
         *     states; the contract's DEL-07 calls it a "13-State Matrix". Resolve
         *     before the email driver is built.
         * @enum {string}
         */
        JobStatus: "Quoted" | "Quote Accepted" | "Drawing – In Progress" | "Drawing – Approved by Client" | "Drawing – Engineering Approval" | "Workshop Notes Compiled" | "Ready to Manufacture" | "Manufacturing Complete" | "Packed" | "Photographed" | "Signed by Workshop Staff" | "QA Approved" | "Invoiced" | "Awaiting Delivery / Install / Pickup" | "Completed" | "On Hold" | "Cancelled";
        /** @enum {string} */
        JobPriority: "Normal" | "High" | "RUSH";
        JobDTO: {
            /** Format: int64 */
            id?: number;
            /** @description Public identifier, e.g. JOB-1001. */
            jobNumber?: string;
            jobName?: string;
            /** @description Set for Quotient-derived jobs. Indexed. */
            quotientQuoteId?: string | null;
            customer?: components["schemas"]["CustomerDTO"];
            status?: components["schemas"]["JobStatus"];
            priority?: components["schemas"]["JobPriority"];
            /**
             * @description DEL-01 §3. False marks a delivery-docket-only job.
             *
             *     Must be its own column. The MVP frontend currently overloads
             *     `manufacturing_required` for this; do not carry that conflation
             *     across — DEL-09 delivery dockets key off this flag.
             */
            needsJobCard?: boolean;
            installRequired?: boolean;
            qaCompleted?: boolean;
            /** Format: date */
            dateRaised?: string;
            dueDate?: string | null;
            quoteValidUntil?: string | null;
            estimatedHours?: number | null;
            raisedBy?: string;
            assignedTo?: string | null;
            alert?: string | null;
            purchaseOrders?: components["schemas"]["PurchaseOrderDTO"][];
            sharePoint?: components["schemas"]["SharePointStateDTO"];
            /** Format: date-time */
            createdDate?: string;
            /** Format: date-time */
            lastModifiedDate?: string;
        };
        CreateJobRequest: {
            /** @description Omit to let the backend allocate via SequenceGeneratorService. */
            jobNumber?: string;
            jobName: string;
            /** Format: int64 */
            customerId: number;
            status?: components["schemas"]["JobStatus"];
            priority?: components["schemas"]["JobPriority"];
            needsJobCard: boolean;
            /** @default false */
            installRequired: boolean;
            /** @default false */
            qaCompleted: boolean;
            /** Format: date */
            dateRaised: string;
            /** Format: date */
            dueDate?: string;
            /** Format: double */
            estimatedHours?: number;
            assignedTo?: string;
            description?: string;
        };
        /** @description Partial update. Absent fields are left untouched. */
        UpdateJobRequest: {
            jobName?: string;
            /** Format: int64 */
            customerId?: number;
            status?: components["schemas"]["JobStatus"];
            priority?: components["schemas"]["JobPriority"];
            needsJobCard?: boolean;
            installRequired?: boolean;
            qaCompleted?: boolean;
            /** Format: date */
            dueDate?: string;
            /** Format: double */
            estimatedHours?: number;
            assignedTo?: string;
            alert?: string;
            /**
             * @description Attribution for the audit trail.
             * @enum {string}
             */
            auditAction?: "job_card_saved" | "status_changed" | "assignment_changed" | "qa_signed_off" | "note_added";
            auditDetail?: string;
        };
        JobAuditEntryDTO: {
            /** Format: int64 */
            id?: number;
            jobNumber?: string;
            action?: string;
            detail?: string;
            performedBy?: string;
            /** Format: date-time */
            performedAt?: string;
        };
        JobKpiSummary: {
            /** @description Status → count. Only non-zero statuses are returned. */
            byStatus?: {
                [key: string]: number;
            };
            byStageGroup?: {
                notStarted?: number;
                manufacturing?: number;
                delivered?: number;
            };
            overdue?: number;
            dueThisWeek?: number;
        };
        CustomerDTO: {
            /** Format: int64 */
            id?: number;
            name: string;
            contactName?: string;
            /** Format: email */
            email?: string;
            phone?: string;
            billingAddress?: string;
            deliveryAddress?: string;
            /**
             * @description Cash customers require invoicing before dispatch (DEL-08).
             * @enum {string}
             */
            accountType?: "CASH" | "ACCOUNT";
            /**
             * @description Master toggle disabling automated client emails (DEL-07).
             * @default true
             */
            notificationsEnabled: boolean;
            readonly activeJobCount?: number;
        };
        QuoteDTO: {
            /** Format: int64 */
            id?: number;
            quoteNumber?: string;
            /** @enum {string} */
            status?: "sent" | "viewed" | "accepted" | "declined" | "expired";
            customer?: components["schemas"]["CustomerDTO"];
            /** Format: double */
            totalAmount?: number;
            currency?: string;
            validUntil?: string | null;
            linkedJobNumber?: string | null;
            lineItems?: {
                description?: string;
                quantity?: number;
                /** Format: double */
                unitPrice?: number;
                /** Format: double */
                total?: number;
            }[];
            events?: {
                eventName?: string;
                /** Format: date-time */
                occurredAt?: string;
            }[];
        };
        /**
         * @description Passed through verbatim to storage. Only `event_name` and the quote
         *     identifier are read at ingestion; everything else is parsed
         *     asynchronously.
         *
         *     **Open question:** DEL-02 requires all 6 Quotient events. The existing
         *     implementation handles 5 (quote_sent, customer_viewed,
         *     customer_question, quote_accepted, quote_declined). Confirm the sixth.
         */
        QuotientWebhookPayload: {
            /** @enum {string} */
            event_name: "quote_sent" | "customer_viewed" | "customer_question" | "quote_accepted" | "quote_declined";
            quote_number?: string;
        } & {
            [key: string]: unknown;
        };
        PurchaseOrderDTO: {
            /** Format: int64 */
            id?: number;
            jobNumber?: string;
            /** @description Indexed for job search. */
            poNumber?: string;
            /** @description Immutable once created. */
            version?: number;
            issuedOn?: string | null;
            /** Format: double */
            totalAmount?: number;
            currency?: string;
            documentUrl?: string | null;
            /** @description Flagged field count. 0 means clean. */
            varianceCount?: number;
            acknowledgedBy?: string | null;
            acknowledgedAt?: string | null;
            /** Format: date-time */
            createdDate?: string;
        };
        VarianceReportDTO: {
            /** Format: int64 */
            purchaseOrderId?: number;
            quoteNumber?: string;
            /** Format: date-time */
            comparedAt?: string;
            fields?: {
                /** @example totalAmount */
                field?: string;
                /** @enum {string} */
                severity?: "PRICE" | "QUANTITY" | "SCOPE";
                quoteValue?: string;
                poValue?: string;
                /** @description Human-readable difference, e.g. '+$420.00 (3.1%)'. */
                delta?: string | null;
            }[];
        };
        SharePointStateDTO: {
            /**
             * @description NOT_CONFIGURED when the org has no SharePoint credentials.
             * @enum {string}
             */
            syncStatus?: "SUCCESS" | "PENDING" | "FAILED" | "NOT_CONFIGURED";
            folderPath?: string | null;
            webUrl?: string | null;
            lastSyncedAt?: string | null;
            lastError?: string | null;
            files?: {
                name?: string;
                /** @enum {string} */
                subfolder?: "Drawings" | "Photos" | "POs";
                /** Format: int64 */
                sizeBytes?: number;
                webUrl?: string;
                /** Format: date-time */
                lastModified?: string;
            }[];
        };
        UploadSessionDTO: {
            /** @description Graph upload session URL. Stream chunks here. */
            uploadUrl?: string;
            /** Format: date-time */
            expiresAt?: string;
            /** @description Must be a multiple of 320 KiB per Graph. */
            chunkSizeBytes?: number;
        };
        PageOfUser: components["schemas"]["PageResponse"] & {
            content?: components["schemas"]["UserDTO"][];
        };
        PageOfRole: components["schemas"]["PageResponse"] & {
            content?: components["schemas"]["RoleDTO"][];
        };
        PageOfPrivilege: components["schemas"]["PageResponse"] & {
            content?: components["schemas"]["PrivilegeDTO"][];
        };
        PageOfOrganization: components["schemas"]["PageResponse"] & {
            content?: components["schemas"]["OrganizationDTO"][];
        };
        PageOfParameter: components["schemas"]["PageResponse"] & {
            content?: components["schemas"]["ApplicationParameterDTO"][];
        };
        PageOfJob: components["schemas"]["PageResponse"] & {
            content?: components["schemas"]["JobDTO"][];
        };
        PageOfJobAudit: components["schemas"]["PageResponse"] & {
            content?: components["schemas"]["JobAuditEntryDTO"][];
        };
        PageOfCustomer: components["schemas"]["PageResponse"] & {
            content?: components["schemas"]["CustomerDTO"][];
        };
        PageOfQuote: components["schemas"]["PageResponse"] & {
            content?: components["schemas"]["QuoteDTO"][];
        };
    };
    responses: {
        /** @description Request accepted. */
        Accepted: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["SuccessResponse"];
            };
        };
        /** @description Missing, expired, or invalid credentials. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ExceptionResponse"];
            };
        };
        /**
         * @description Authenticated but lacking the required privilege. Also returned when an
         *     endpoint has no privilege mapping at all — the interceptor is
         *     deny-by-default, so an unmapped endpoint is closed, not open.
         */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ExceptionResponse"];
            };
        };
        /** @description Not found, or outside the caller's organization. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ExceptionResponse"];
            };
        };
        /** @description Request failed validation. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "businessErrorCode": 400,
                 *       "error": "Validation failed",
                 *       "errors": {
                 *         "jobNumber": "must match JOB-<number>",
                 *         "customerId": "must not be null"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ExceptionResponse"];
            };
        };
    };
    parameters: {
        /** @description 0-based page index. */
        Page: number;
        Size: number;
        IdPath: number;
        /** @description Public job number, e.g. `JOB-1001` or `JOB-Q-4821`. */
        JobNumberPath: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    authenticate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthenticationRequest"];
            };
        };
        responses: {
            /** @description Authenticated, or an MFA challenge issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Account locked after repeated failed attempts. */
            423: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExceptionResponse"];
                };
            };
        };
    };
    verifyMfa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaVerifyRequest"];
            };
        };
        responses: {
            /** @description Verified — tokens issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description New token pair. The presented refresh token is revoked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDTO"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMyProfileRequest"];
            };
        };
        responses: {
            /** @description Updated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDTO"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
        };
    };
    setupMfa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Secret and QR code. Not yet active until confirmed via enable. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MfaSetupResponse"];
                };
            };
        };
    };
    enableMfa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaCodeRequest"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            400: components["responses"]["ValidationError"];
        };
    };
    disableMfa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaDisableRequest"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            400: components["responses"]["ValidationError"];
        };
    };
    listUsers: {
        parameters: {
            query?: {
                /** @description 0-based page index. */
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paged users. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageOfUser"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description Updated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDTO"];
                };
            };
            400: components["responses"]["ValidationError"];
            403: components["responses"]["Forbidden"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Created user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDTO"];
                };
            };
            400: components["responses"]["ValidationError"];
            403: components["responses"]["Forbidden"];
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDTO"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    disableUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Disabled user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDTO"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    listRoles: {
        parameters: {
            query?: {
                /** @description 0-based page index. */
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paged roles. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageOfRole"];
                };
            };
        };
    };
    updateRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleDTO"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
        };
    };
    createRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleDTO"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            400: components["responses"]["ValidationError"];
        };
    };
    listPrivileges: {
        parameters: {
            query?: {
                /** @description 0-based page index. */
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
                privilegeType?: "ACTION" | "MENU" | "FIELD";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paged privileges. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageOfPrivilege"];
                };
            };
        };
    };
    createPrivilege: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrivilegeDTO"];
            };
        };
        responses: {
            /** @description Created privilege. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrivilegeDTO"];
                };
            };
        };
    };
    listOrganizations: {
        parameters: {
            query?: {
                /** @description 0-based page index. */
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paged organizations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageOfOrganization"];
                };
            };
        };
    };
    createOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrganizationRequest"];
            };
        };
        responses: {
            /** @description Provisioned organization and admin login. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationProvisionResponse"];
                };
            };
        };
    };
    listGlobalParameters: {
        parameters: {
            query?: {
                /** @description 0-based page index. */
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paged parameters. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageOfParameter"];
                };
            };
        };
    };
    upsertGlobalParameter: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationParameterDTO"];
            };
        };
        responses: {
            /** @description Saved parameter. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationParameterDTO"];
                };
            };
        };
    };
    listOrgParameters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Effective parameters. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationParameterDTO"][];
                };
            };
        };
    };
    upsertOrgParameter: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationParameterDTO"];
            };
        };
        responses: {
            /** @description Saved parameter. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationParameterDTO"];
                };
            };
        };
    };
    listJobs: {
        parameters: {
            query?: {
                /** @description 0-based page index. */
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
                /** @description Free text across jobNumber, jobName, poNumber, customerName. */
                search?: string;
                /** @description Repeatable. Filters to any of the supplied statuses. */
                status?: components["schemas"]["JobStatus"][];
                /** @description Coarse bucket used by dashboard deep links. */
                stageGroup?: "not-started" | "manufacturing" | "delivered";
                priority?: components["schemas"]["JobPriority"];
                customerId?: number;
                /** @description `field,asc|desc` — e.g. `dueDate,asc`. */
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paged jobs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageOfJob"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    createJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJobRequest"];
            };
        };
        responses: {
            /** @description Created job. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDTO"];
                };
            };
            400: components["responses"]["ValidationError"];
            /** @description Job number already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExceptionResponse"];
                };
            };
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Public job number, e.g. `JOB-1001` or `JOB-Q-4821`. */
                jobNumber: components["parameters"]["JobNumberPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDTO"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Public job number, e.g. `JOB-1001` or `JOB-Q-4821`. */
                jobNumber: components["parameters"]["JobNumberPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateJobRequest"];
            };
        };
        responses: {
            /** @description Updated job. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDTO"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
        };
    };
    listJobAudit: {
        parameters: {
            query?: {
                /** @description 0-based page index. */
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path: {
                /** @description Public job number, e.g. `JOB-1001` or `JOB-Q-4821`. */
                jobNumber: components["parameters"]["JobNumberPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paged audit entries, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageOfJobAudit"];
                };
            };
        };
    };
    getJobKpis: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Counts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobKpiSummary"];
                };
            };
        };
    };
    listCustomers: {
        parameters: {
            query?: {
                /** @description 0-based page index. */
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paged customers. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageOfCustomer"];
                };
            };
        };
    };
    createCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerDTO"];
            };
        };
        responses: {
            /** @description Created customer. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerDTO"];
                };
            };
        };
    };
    getCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Customer. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerDTO"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerDTO"];
            };
        };
        responses: {
            /** @description Updated customer. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerDTO"];
                };
            };
        };
    };
    listQuotes: {
        parameters: {
            query?: {
                /** @description 0-based page index. */
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
                status?: "sent" | "viewed" | "accepted" | "declined" | "expired";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paged quotes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageOfQuote"];
                };
            };
        };
    };
    getQuote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quoteNumber: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Quote. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteDTO"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    ingestQuotientWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuotientWebhookPayload"];
            };
        };
        responses: {
            /** @description Payload archived and queued. Always returned on a valid secret. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok?: boolean;
                        /** Format: uuid */
                        eventId?: string;
                    };
                };
            };
            /** @description Missing or invalid shared secret. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExceptionResponse"];
                };
            };
        };
    };
    listJobPurchaseOrders: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Public job number, e.g. `JOB-1001` or `JOB-Q-4821`. */
                jobNumber: components["parameters"]["JobNumberPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Purchase orders. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurchaseOrderDTO"][];
                };
            };
        };
    };
    createPurchaseOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Public job number, e.g. `JOB-1001` or `JOB-Q-4821`. */
                jobNumber: components["parameters"]["JobNumberPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    poNumber: string;
                    /** Format: date */
                    issuedOn?: string;
                    /** Format: double */
                    totalAmount?: number;
                    /** @default AUD */
                    currency?: string;
                    /**
                     * Format: binary
                     * @description The PO PDF, stored alongside this version.
                     */
                    document?: string;
                };
            };
        };
        responses: {
            /** @description Created PO version with variance report. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurchaseOrderDTO"];
                };
            };
            400: components["responses"]["ValidationError"];
        };
    };
    getPurchaseOrderVariance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Variance report. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VarianceReportDTO"];
                };
            };
        };
    };
    acknowledgePurchaseOrderVariance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    note?: string;
                };
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
        };
    };
    getJobSharePointState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Public job number, e.g. `JOB-1001` or `JOB-Q-4821`. */
                jobNumber: components["parameters"]["JobNumberPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sync state and folder contents. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SharePointStateDTO"];
                };
            };
        };
    };
    provisionJobSharePointFolder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Public job number, e.g. `JOB-1001` or `JOB-Q-4821`. */
                jobNumber: components["parameters"]["JobNumberPath"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Admin override for the default path (DEL-04 §3). */
                    folderPathOverride?: string;
                };
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            /** @description SharePoint not configured or Graph unreachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExceptionResponse"];
                };
            };
        };
    };
    createSharePointUploadSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Public job number, e.g. `JOB-1001` or `JOB-Q-4821`. */
                jobNumber: components["parameters"]["JobNumberPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    fileName: string;
                    /** Format: int64 */
                    sizeBytes: number;
                    /** @enum {string} */
                    subfolder: "Drawings" | "Photos" | "POs";
                };
            };
        };
        responses: {
            /** @description Upload session. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSessionDTO"];
                };
            };
        };
    };
}
