import type { FieldAccessMode, PrivilegeType } from "@/lib/frp/privilege-types";

export type { FieldAccessMode, PrivilegeType };

export interface AuthenticationResponse {
  token?: string;
  refreshToken?: string;
  expiresIn?: number;
  requires2fa?: boolean;
  mfaToken?: string;
}

export interface MfaSetupResponse {
  secret: string;
  otpAuthUri: string;
  qrCodeDataUri: string;
}

export interface ApplicationParameterDTO {
  id?: number | null;
  paramName: string;
  paramValue?: string | null;
  paramType?: string | null;
  description?: string | null;
  organizationId?: number | null;
  orgEditable?: boolean | null;
  inherited?: boolean;
}

export type JobEmailRecipientCategory =
  | "JOB_LIFECYCLE"
  | "DOCUMENTS"
  | "APPROVALS"
  | "FINANCE";

export interface JobEmailEventDef {
  category: JobEmailRecipientCategory;
  eventKey: string;
  event: string;
  eventName?: string | null;
  description?: string | null;
  /** -1 not applicable, 0 optional, 1 required (document upload events). */
  documentAttachmentRequired?: number | null;
}

export interface JobEmailRecipientDTO {
  id?: number | null;
  eventDef?: JobEmailEventDef | null;
  assigningTrigger?: boolean | null;
  customerTriggered?: boolean | null;
  otherUserIds?: string | null;
  customerSideRecipients?: string | null;
  clientSideRecipients?: string | null;
  totalRecipients?: number | null;
  orgEditable?: boolean | null;
  enabled?: boolean | null;
  inherited?: boolean | null;
  /** Platform default; org cannot enable attachment when this is -1. */
  platformDocumentAttachmentRequired?: number | null;
}

/** Quotient integration setup (GET/PUT /integrations/quotient). */
export interface QuotientIntegrationDTO {
  enabled?: boolean | null;
  baseUrl?: string | null;
  jobTriggerEvents?: string | null;
  /** Read-only: id of the active webhook token row, for revoking it. */
  webhookTokenId?: number | null;
  /** Read-only: secret carried in the webhook URL; generated by the backend. */
  webhookToken?: string | null;
  /** Read-only: full URL to paste into Quotient. */
  webhookUrl?: string | null;
  /** On generate: requested expiry (optional). On read: the active token's expiry. */
  webhookExpiresAt?: string | null;
  /** Read-only: true when a valid webhook token is configured. */
  webhookConfigured?: boolean | null;
}

/** A stored, revocable integration credential (/integrations/{provider}/api-key). */
export interface IntegrationApiKeyDTO {
  id?: number | null;
  provider?: string | null;
  /** Write-only on issue; never returned. */
  apiKey?: string | null;
  /** Read-only masked form, e.g. "****abcd". */
  maskedKey?: string | null;
  expiresAt?: string | null;
  createdBy?: number | null;
  createdAt?: string | null;
  revokedAt?: string | null;
  active?: boolean | null;
}

export interface OrganizationDTO {
  id?: number;
  companyName?: string;
  companyCode?: string;
  address?: string;
  city?: string;
  country?: string;
  postalCode?: string;
  phone?: string;
  mobileNumber?: string;
  email?: string;
  gstNo?: string;
  /** ISO 4217 code from the org (e.g. AUD, GBP). */
  currency?: string;
}

export interface CreateOrganizationRequest {
  companyName: string;
  companyCode: string;
  address?: string;
  city?: string;
  country?: string;
  postalCode?: string;
  phone?: string;
  mobileNumber?: string;
  email?: string;
  gstNo?: string;
  currency?: string;
  adminPassword: string;
  adminEmail: string;
  adminDisplayName: string;
  adminMobileNumber?: string;
}

export interface OrganizationProvisionResponse {
  organization: OrganizationDTO;
  /** Login identity for the provisioned admin (email). */
  adminUsername: string;
}

export interface PageResponse<T> {
  content: T[];
  number: number;
  size: number;
  totalElements: number;
  totalPages: number;
  first: boolean;
  last: boolean;
}

export interface UserDTO {
  id?: number;
  username?: string;
  displayName?: string;
  email?: string;
  mobileNumber?: string;
  locale?: string;
  designation?: string;
  authProvider?: string;
  organization?: OrganizationDTO | null;
  rolesPrivileges?: string[];
  roleIds?: number[];
  roleCodes?: string[];
  enabled?: boolean;
  totpEnabled?: boolean;
  mfaAvailable?: boolean;
}

export interface CreateUserRequest {
  email: string;
  password: string;
  displayName: string;
  mobileNumber?: string;
  roleIds: number[];
}

export interface UpdateUserRequest {
  id: number;
  displayName: string;
  mobileNumber?: string;
  enabled?: boolean;
  roleIds: number[];
  password?: string;
}

export interface RoleDTO {
  id?: number;
  role: string;
  roleCode: string;
  privilegeCodes: string[];
}

export interface PrivilegeDTO {
  id?: number;
  privilege?: string;
  privilegeCode: string;
  /** Backend enum: ACTION | MENU | FIELD — never VIEW. */
  privilegeType?: PrivilegeType;
  domain?: string;
  fieldKey?: string;
  /** FIELD only: READ | WRITE. */
  accessMode?: FieldAccessMode;
  parentId?: number | null;
  sortOrder?: number;
  platformOnly?: boolean;
  systemManaged?: boolean;
  active?: boolean;
}

/* ------------------------------------------------- job chat & notifications */

/** `com.argus.frp.Enum.MessageTag`. */
export type MessageTag = "QUESTION" | "BLOCKER" | "UPDATE" | "HANDOVER";

/** One message on a job thread — `GET/POST /jobs/{id}/messages`. */
export interface GroupChatDTO {
  id?: number;
  jobId?: number;
  body: string;
  tag?: MessageTag | null;
  /**
   * Read-only. The server parses `@all` from the body at post time; a value
   * sent on a request is ignored.
   */
  mentionsAll?: boolean;
  /**
   * Client-minted idempotency key. Send one on every post: without it a retry
   * after a dropped connection posts the message twice.
   */
  clientMsgId?: string | null;
  sentBy?: number;
  /** Resolved server-side, so the client never has to look users up. */
  sentByName?: string | null;
  sentByInitials?: string | null;
  /** ISO-8601. */
  sentAt?: string;
}

/** `com.argus.frp.Enum.NotificationType`. One value today. */
export type NotificationType = "CHAT_MENTION_ALL";

/** One row in the notification panel. */
export interface NotificationDTO {
  id: number;
  type: NotificationType;
  jobId?: number | null;
  /** Human-facing job number, for the deep link. */
  jobNumber?: string | null;
  messageId?: number | null;
  actorUserId?: number | null;
  actorName?: string | null;
  title: string;
  bodyPreview?: string | null;
  /** Null means unread — what the red dot reflects. */
  readAt?: string | null;
  createdAt?: string;
}

/** The badge poll's whole payload. Deliberately tiny. */
export interface NotificationSummaryDTO {
  unreadCount: number;
  /** Highest unread id; null when nothing is unread. */
  latestId?: number | null;
}

export class FrpApiError extends Error {
  status: number;
  body: unknown;

  constructor(status: number, message: string, body?: unknown) {
    super(message);
    this.name = "FrpApiError";
    this.status = status;
    this.body = body;
  }
}
