"use client";

import { useCallback, useEffect, useState } from "react";
import {
  getQuotientIntegration,
  regenerateQuotientWebhookToken,
} from "@/lib/frp/api";
import type { QuotientIntegrationDTO } from "@/lib/frp/types";
import { FrpApiError } from "@/lib/frp/types";

const inputClass =
  "mt-1.5 w-full min-h-[42px] rounded-[14px] border border-[#E2E8F0] bg-white px-3 text-sm font-medium text-[#0F172A] shadow-sm outline-none transition-shadow placeholder:text-slate-400 focus:border-[#2563EB] focus:ring-2 focus:ring-[#2563EB]/20";
const labelClass =
  "block text-[10px] font-semibold uppercase tracking-wide text-slate-500";

function errText(err: unknown, fallback: string): string {
  if (err instanceof FrpApiError) return err.message;
  if (err instanceof Error) return err.message;
  return fallback;
}

/**
 * Sits inside the generic Quotient parameter group and adds the two things the
 * raw parameter fields cannot do: generate the QUOTIENT_WEBHOOK_TOKEN on the
 * server and show the ready-to-paste webhook URL. onTokenGenerated lets the
 * parent reload the parameter values after the token changes.
 */
export default function QuotientWebhookHelper({
  onTokenGenerated,
}: {
  onTokenGenerated?: () => void;
}) {
  const [cfg, setCfg] = useState<QuotientIntegrationDTO | null>(null);
  const [busy, setBusy] = useState(false);
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => {
    try {
      setCfg(await getQuotientIntegration());
    } catch (err) {
      setError(errText(err, "Failed to load webhook"));
    }
  }, []);

  useEffect(() => {
    void load();
  }, [load]);

  async function generate() {
    setBusy(true);
    setError(null);
    try {
      setCfg(await regenerateQuotientWebhookToken());
      onTokenGenerated?.();
    } catch (err) {
      setError(errText(err, "Failed to generate token"));
    } finally {
      setBusy(false);
    }
  }

  async function copy() {
    if (!cfg?.webhookUrl) return;
    try {
      await navigator.clipboard.writeText(cfg.webhookUrl);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      /* clipboard blocked; the field stays selectable as a fallback */
    }
  }

  return (
    <div className="border-t border-slate-200 pt-4">
      <label className={labelClass} htmlFor="quotient-webhook-url">
        Webhook URL
      </label>
      <p className="mt-0.5 text-xs text-slate-500">
        Generated by the backend from QUOTIENT_WEBHOOK_TOKEN. Paste it into
        Quotient → Account Settings → Webhooks.
      </p>
      {error && <p className="mt-1 text-xs text-red-600">{error}</p>}
      <div className="mt-1.5 flex flex-wrap gap-2">
        <input
          id="quotient-webhook-url"
          readOnly
          className={`${inputClass} !mt-0 min-w-[240px] flex-1 font-mono text-xs`}
          value={cfg?.webhookUrl ?? "Generate a token to build the URL"}
          onFocus={(e) => e.currentTarget.select()}
        />
        <button
          type="button"
          onClick={() => void copy()}
          disabled={!cfg?.webhookUrl}
          className="btn-secondary shrink-0 disabled:opacity-60"
        >
          {copied ? "Copied" : "Copy"}
        </button>
        <button
          type="button"
          onClick={() => void generate()}
          disabled={busy}
          className="btn-secondary shrink-0 disabled:opacity-60"
        >
          {busy ? "Generating…" : "Generate token"}
        </button>
      </div>
    </div>
  );
}
