"use client";

import { useState } from "react";
import { regenerateQuotientWebhookToken } from "@/lib/frp/api";
import { FrpApiError } from "@/lib/frp/types";

function errText(err: unknown, fallback: string): string {
  if (err instanceof FrpApiError) return err.message;
  if (err instanceof Error) return err.message;
  return fallback;
}

/**
 * The one thing raw parameter fields cannot do: generate the webhook token on
 * the server. Generating does NOT persist - it returns the fresh token and
 * assembled URL, which the parent drops into the read-only fields. They are
 * saved to the parameters only when the group is saved.
 */
export default function QuotientWebhookHelper({
  onGenerated,
}: {
  onGenerated: (token: string, url: string) => void;
}) {
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function generate() {
    setBusy(true);
    setError(null);
    try {
      const resp = await regenerateQuotientWebhookToken();
      onGenerated(resp.webhookToken ?? "", resp.webhookUrl ?? "");
    } catch (err) {
      setError(errText(err, "Failed to generate token"));
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="border-t border-slate-200 pt-4">
      <p className="text-xs text-slate-500">
        The webhook token and URL are generated by the backend, not typed.
        Generate the token, then click Save to store it in the parameters and
        copy QUOTIENT_WEBHOOK_URL into Quotient → Account Settings → Webhooks.
      </p>
      {error && <p className="mt-1 text-xs text-red-600">{error}</p>}
      <button
        type="button"
        onClick={() => void generate()}
        disabled={busy}
        className="btn-secondary mt-2 disabled:opacity-60"
      >
        {busy ? "Generating…" : "Generate webhook token"}
      </button>
    </div>
  );
}
