import type { AuditLogEntry } from "@/lib/administration/types";

export const AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: "audit-1",
    timestamp: "2026-08-03 14:32:01 UTC-4",
    userName: "David Kim",
    userRole: "Admin",
    action: "UPDATE_RECORD",
    targetType: "Job",
    targetLabel: "Job #492",
    detailFrom: "Status: Pending",
    detailTo: "Status: Active",
    ipAddress: "192.168.1.105",
    device: "Chrome / MacOS",
  },
  {
    id: "audit-2",
    timestamp: "2026-08-03 13:15:44 UTC-4",
    userName: "Sarah Jenkins",
    userRole: "Technician",
    action: "CREATE_RECORD",
    targetType: "Quote",
    targetLabel: "Quote #811",
    detailText: "Created new quote for client 'Acme Corp'",
    ipAddress: "10.0.0.42",
    device: "Safari / iOS",
  },
  {
    id: "audit-3",
    timestamp: "2026-08-03 11:02:19 UTC-4",
    userName: "System API",
    userRole: "Automated",
    action: "DELETE_RECORD",
    targetType: "UserSession",
    targetLabel: "UserSession",
    detailText: "Cleared expired session token (ID: a8f9…2b)",
    ipAddress: "127.0.0.1",
    device: "Node.js Server",
  },
  {
    id: "audit-4",
    timestamp: "2026-08-03 09:45:00 UTC-4",
    userName: "Admin User",
    userRole: "Operations Manager",
    action: "AUTH_LOGIN",
    targetType: "Authentication",
    targetLabel: "Authentication",
    detailText: "Successful login via SSO",
    ipAddress: "203.0.113.45",
    device: "Firefox / Windows 11",
  },
  {
    id: "audit-5",
    timestamp: "2026-08-02 17:08:12 UTC-4",
    userName: "Marcus Chen",
    userRole: "System Admin",
    action: "UPDATE_RECORD",
    targetType: "Role",
    targetLabel: "Support Specialist",
    detailFrom: "Permissions: 42",
    detailTo: "Permissions: 45",
    ipAddress: "10.0.0.18",
    device: "Chrome / Windows 11",
  },
  {
    id: "audit-6",
    timestamp: "2026-08-02 10:52:37 UTC-4",
    userName: "Neha Singh",
    userRole: "Support Specialist",
    action: "CREATE_RECORD",
    targetType: "User",
    targetLabel: "Amos Burton",
    detailText: "Created user account with Workshop role",
    ipAddress: "10.0.0.63",
    device: "Edge / Windows 11",
  },
  {
    id: "audit-7",
    timestamp: "2026-08-01 16:41:09 UTC-4",
    userName: "Admin User",
    userRole: "Operations Manager",
    action: "UPDATE_RECORD",
    targetType: "Privilege",
    targetLabel: "jobs.delete",
    detailFrom: "Status: Active",
    detailTo: "Status: Restricted",
    ipAddress: "203.0.113.45",
    device: "Firefox / Windows 11",
  },
];

export const AUDIT_ACTION_FILTERS = ["All Actions", "CREATE_RECORD", "UPDATE_RECORD", "DELETE_RECORD", "AUTH_LOGIN"] as const;
export const AUDIT_DATE_RANGES = ["Last 7 Days", "Last 30 Days", "Last 90 Days", "Custom Range"] as const;
