import type { AuditLogEntry } from "@/lib/administration/types";

export const AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: "audit-1",
    timestamp: "2026-08-03 14:32:01 UTC-4",
    userName: "Sarah Jenkins",
    userRole: "Org Admin",
    action: "UPDATE_RECORD",
    targetType: "User",
    targetLabel: "David Chen",
    detailFrom: "Status: Active",
    detailTo: "Status: Inactive",
    ipAddress: "192.168.1.105",
    device: "Chrome / Windows 11",
  },
  {
    id: "audit-2",
    timestamp: "2026-08-03 13:15:44 UTC-4",
    userName: "FRP Super Admin",
    userRole: "Super Admin",
    action: "CREATE_RECORD",
    targetType: "Organization",
    targetLabel: "Acme Fabrication Co.",
    detailText: "Provisioned new tenant organization with Org Admin sarah.jenkins@frpengineering.com",
    ipAddress: "10.0.0.42",
    device: "Chrome / MacOS",
  },
  {
    id: "audit-3",
    timestamp: "2026-08-03 11:02:19 UTC-4",
    userName: "System",
    userRole: "Automated",
    action: "DELETE_RECORD",
    targetType: "Session",
    targetLabel: "Expired refresh token",
    detailText: "Cleared expired session token (ID: a8f9…2b)",
    ipAddress: "127.0.0.1",
    device: "Node.js Server",
  },
  {
    id: "audit-4",
    timestamp: "2026-08-03 09:45:00 UTC-4",
    userName: "Sarah Jenkins",
    userRole: "Org Admin",
    action: "AUTH_LOGIN",
    targetType: "Authentication",
    targetLabel: "Authentication",
    detailText: "Successful login",
    ipAddress: "203.0.113.45",
    device: "Firefox / Windows 11",
  },
  {
    id: "audit-5",
    timestamp: "2026-08-02 17:08:12 UTC-4",
    userName: "David Kim",
    userRole: "Org Admin",
    action: "UPDATE_RECORD",
    targetType: "Role",
    targetLabel: "Support Specialist",
    detailFrom: "Permissions: 8",
    detailTo: "Permissions: 9",
    ipAddress: "10.0.0.18",
    device: "Chrome / Windows 11",
  },
  {
    id: "audit-6",
    timestamp: "2026-08-02 10:52:37 UTC-4",
    userName: "Neha Singh",
    userRole: "Support Specialist",
    action: "CREATE_RECORD",
    targetType: "User",
    targetLabel: "Amos Burton",
    detailText: "Created user account with Field Engineer role",
    ipAddress: "10.0.0.63",
    device: "Edge / Windows 11",
  },
  {
    id: "audit-7",
    timestamp: "2026-08-01 16:41:09 UTC-4",
    userName: "Sarah Jenkins",
    userRole: "Org Admin",
    action: "UPDATE_RECORD",
    targetType: "Privilege",
    targetLabel: "MFA_TOTP_ENABLED",
    detailText: "Enabled MFA requirement for the Org Admin role",
    ipAddress: "203.0.113.45",
    device: "Firefox / Windows 11",
  },
  {
    id: "audit-8",
    timestamp: "2026-08-01 08:12:53 UTC-4",
    userName: "David Chen",
    userRole: "Field Engineer",
    action: "AUTH_LOGIN",
    targetType: "Authentication",
    targetLabel: "Authentication",
    detailText: "Successful login",
    ipAddress: "10.1.4.22",
    device: "Chrome / Android",
  },
];

export const AUDIT_ACTION_FILTERS = ["All Actions", "CREATE_RECORD", "UPDATE_RECORD", "DELETE_RECORD", "AUTH_LOGIN"] as const;
export const AUDIT_DATE_RANGES = ["Last 7 Days", "Last 30 Days", "Last 90 Days", "Custom Range"] as const;
