import type { Privilege } from "@/lib/administration/types";

// Mirrors the real backend catalog in com.argus.frp.constants.PrivilegeCodes.
// "restricted" = platform-only (Super Admin can use it, Org Admin cannot).
export const PRIVILEGES: Privilege[] = [
  {
    id: "priv-organization-create",
    code: "ORGANIZATION_CREATE",
    description: "Allows provisioning new tenant organizations on the platform.",
    module: "Organizations",
    usedByRoles: ["Super Admin"],
    status: "restricted",
  },
  {
    id: "priv-organization-read-all",
    code: "ORGANIZATION_READ_ALL",
    description: "Allows viewing every organization across the platform.",
    module: "Organizations",
    usedByRoles: ["Super Admin"],
    status: "restricted",
  },
  {
    id: "priv-organization-update",
    code: "ORGANIZATION_UPDATE",
    description: "Allows editing an organization's profile and settings.",
    module: "Organizations",
    usedByRoles: ["Super Admin"],
    status: "restricted",
  },
  {
    id: "priv-organization-disable",
    code: "ORGANIZATION_DISABLE",
    description: "Allows disabling a tenant organization and its access.",
    module: "Organizations",
    usedByRoles: ["Super Admin"],
    status: "restricted",
  },
  {
    id: "priv-privilege-read",
    code: "PRIVILEGE_READ",
    description: "Allows viewing the catalog of system privileges.",
    module: "Privileges",
    usedByRoles: ["Super Admin", "Org Admin"],
    status: "active",
  },
  {
    id: "priv-privilege-manage",
    code: "PRIVILEGE_MANAGE",
    description: "Allows creating, editing, and retiring system privileges.",
    module: "Privileges",
    usedByRoles: ["Super Admin"],
    status: "restricted",
  },
  {
    id: "priv-cache-refresh",
    code: "CACHE_REFRESH",
    description: "Allows manually clearing and rebuilding server-side caches.",
    module: "System",
    usedByRoles: ["Super Admin"],
    status: "restricted",
  },
  {
    id: "priv-param-manage",
    code: "PARAM_MANAGE",
    description: "Allows editing platform-wide configuration parameters.",
    module: "System",
    usedByRoles: ["Super Admin"],
    status: "restricted",
  },
  {
    id: "priv-integration-param-manage",
    code: "INTEGRATION_PARAM_MANAGE",
    description: "Allows editing an organization's integration settings (SharePoint, Quotient).",
    module: "System",
    usedByRoles: ["Super Admin", "Org Admin"],
    status: "active",
  },
  {
    id: "priv-mfa-totp-enabled",
    code: "MFA_TOTP_ENABLED",
    description: "Marks whether an account has TOTP-based multi-factor authentication turned on.",
    module: "Security",
    usedByRoles: ["Org Admin"],
    status: "active",
  },
  {
    id: "priv-role-create",
    code: "ROLE_CREATE",
    description: "Allows creating new roles.",
    module: "Roles",
    usedByRoles: ["Super Admin", "Org Admin"],
    status: "active",
  },
  {
    id: "priv-role-read",
    code: "ROLE_READ",
    description: "Allows viewing existing roles and their privileges.",
    module: "Roles",
    usedByRoles: ["Super Admin", "Org Admin"],
    status: "active",
  },
  {
    id: "priv-role-update",
    code: "ROLE_UPDATE",
    description: "Allows editing a role's name, description, and privileges.",
    module: "Roles",
    usedByRoles: ["Super Admin", "Org Admin"],
    status: "active",
  },
  {
    id: "priv-role-delete",
    code: "ROLE_DELETE",
    description: "Allows permanently deleting a role.",
    module: "Roles",
    usedByRoles: ["Super Admin", "Org Admin"],
    status: "active",
  },
  {
    id: "priv-user-create",
    code: "USER_CREATE",
    description: "Allows creating new user accounts.",
    module: "Users",
    usedByRoles: ["Super Admin", "Org Admin"],
    status: "active",
  },
  {
    id: "priv-user-read",
    code: "USER_READ",
    description: "Allows viewing user accounts and their details.",
    module: "Users",
    usedByRoles: ["Super Admin", "Org Admin"],
    status: "active",
  },
  {
    id: "priv-user-update",
    code: "USER_UPDATE",
    description: "Allows editing a user's profile, department, or roles.",
    module: "Users",
    usedByRoles: ["Super Admin", "Org Admin"],
    status: "active",
  },
  {
    id: "priv-user-disable",
    code: "USER_DISABLE",
    description: "Allows disabling a user's account and login access.",
    module: "Users",
    usedByRoles: ["Super Admin", "Org Admin"],
    status: "active",
  },
];

export const PRIVILEGE_MODULES = [
  "All Modules",
  "Organizations",
  "Users",
  "Roles",
  "Privileges",
  "System",
  "Security",
] as const;
