import type { Privilege } from "@/lib/administration/types";

export const PRIVILEGES: Privilege[] = [
  {
    id: "priv-users-view",
    code: "users.view",
    description: "Allows viewing of user profiles and lists.",
    module: "Users",
    usedByRoles: ["Administrator", "Operations Manager", "Guest Viewer"],
    status: "active",
  },
  {
    id: "priv-users-edit",
    code: "users.edit",
    description: "Allows modification of existing user details.",
    module: "Users",
    usedByRoles: ["Administrator", "Operations Manager"],
    status: "active",
  },
  {
    id: "priv-jobs-delete",
    code: "jobs.delete",
    description: "Allows permanent deletion of job records.",
    module: "Jobs",
    usedByRoles: ["Administrator"],
    status: "restricted",
  },
  {
    id: "priv-system-config",
    code: "system.config",
    description: "Access to global system configuration settings.",
    module: "System",
    usedByRoles: ["Administrator"],
    status: "active",
  },
  {
    id: "priv-legacy-feature-x",
    code: "legacy.feature_x",
    description: "Deprecated feature flag. Do not use.",
    module: "System",
    usedByRoles: [],
    status: "inactive",
  },
  {
    id: "priv-jobs-view",
    code: "jobs.view",
    description: "Allows viewing of assigned and unassigned job records.",
    module: "Jobs",
    usedByRoles: ["Administrator", "Operations Manager", "Field Engineer"],
    status: "active",
  },
  {
    id: "priv-jobs-edit",
    code: "jobs.edit",
    description: "Allows updating job status and field data.",
    module: "Jobs",
    usedByRoles: ["Administrator", "Operations Manager", "Field Engineer"],
    status: "active",
  },
  {
    id: "priv-quotes-view",
    code: "quotes.view",
    description: "Allows viewing of customer quotes and pricing.",
    module: "Quotes",
    usedByRoles: ["Administrator", "Operations Manager", "Support Specialist"],
    status: "active",
  },
  {
    id: "priv-quotes-approve",
    code: "quotes.approve",
    description: "Allows approving or declining pending quotes.",
    module: "Quotes",
    usedByRoles: ["Administrator", "Operations Manager"],
    status: "active",
  },
  {
    id: "priv-users-disable",
    code: "users.disable",
    description: "Allows disabling active user accounts.",
    module: "Users",
    usedByRoles: ["Administrator"],
    status: "restricted",
  },
  {
    id: "priv-system-audit-export",
    code: "system.audit_export",
    description: "Allows exporting the full audit log to CSV.",
    module: "System",
    usedByRoles: ["Administrator"],
    status: "active",
  },
  {
    id: "priv-jobs-create",
    code: "jobs.create",
    description: "Allows creating new fabrication job records.",
    module: "Jobs",
    usedByRoles: ["Administrator", "Operations Manager"],
    status: "active",
  },
];

export const PRIVILEGE_MODULES = ["All Modules", "Users", "Jobs", "Quotes", "System"] as const;
