import type { AdminUser } from "@/lib/administration/types";

function initials(first: string, last: string): string {
  return `${first[0]}${last[0]}`.toUpperCase();
}

const AVATAR_COLORS = [
  "bg-orange-100 text-orange-700",
  "bg-blue-100 text-blue-700",
  "bg-emerald-100 text-emerald-700",
  "bg-violet-100 text-violet-700",
  "bg-rose-100 text-rose-700",
  "bg-slate-200 text-slate-700",
];

function colorFor(seed: number): string {
  return AVATAR_COLORS[seed % AVATAR_COLORS.length];
}

interface Seed {
  firstName: string;
  lastName: string;
  email: string;
  department: string;
  roleIds: string[];
  roleNames: string[];
  status: AdminUser["status"];
  lastLogin: string | null;
  failedAttempts?: number;
  region: AdminUser["region"];
  createdAt: string;
}

const SEEDS: Seed[] = [
  {
    firstName: "Sarah",
    lastName: "Jenkins",
    email: "s.jenkins@frpengineering.com",
    department: "Admin / Accounts",
    roleIds: ["role-org-admin"],
    roleNames: ["Org Admin"],
    status: "active",
    lastLogin: "2 mins ago",
    region: "North America",
    createdAt: "2025-11-02T09:00:00Z",
  },
  {
    firstName: "Marcus",
    lastName: "Thorne",
    email: "m.thorne@frpengineering.com",
    department: "Project Managers",
    roleIds: ["role-operations-manager"],
    roleNames: ["Operations Manager"],
    status: "active",
    lastLogin: "Oct 24, 09:15 AM",
    region: "North America",
    createdAt: "2025-08-14T09:00:00Z",
  },
  {
    firstName: "David",
    lastName: "Chen",
    email: "d.chen@frpengineering.com",
    department: "Workshop / Field",
    roleIds: ["role-field-engineer"],
    roleNames: ["Field Engineer"],
    status: "inactive",
    lastLogin: "Sep 12, 14:30 PM",
    region: "Asia Pacific",
    createdAt: "2024-12-01T09:00:00Z",
  },
  {
    firstName: "Elena",
    lastName: "Rostova",
    email: "e.rostova@frpengineering.com",
    department: "Workshop / Field",
    roleIds: ["role-field-engineer"],
    roleNames: ["Field Engineer"],
    status: "active",
    lastLogin: "Oct 23, 11:45 AM",
    region: "Europe",
    createdAt: "2025-03-19T09:00:00Z",
  },
  {
    firstName: "James",
    lastName: "Baxter",
    email: "j.baxter@frpengineering.com",
    department: "Sales / QA",
    roleIds: ["role-guest-viewer"],
    roleNames: ["Guest Viewer"],
    status: "locked",
    lastLogin: null,
    failedAttempts: 5,
    region: "North America",
    createdAt: "2026-01-05T09:00:00Z",
  },
  {
    firstName: "Rahul",
    lastName: "Sharma",
    email: "r.sharma@frpengineering.com",
    department: "Draftsmen",
    roleIds: ["role-support-specialist"],
    roleNames: ["Support Specialist"],
    status: "active",
    lastLogin: "Oct 22, 08:05 AM",
    region: "Asia Pacific",
    createdAt: "2025-05-27T09:00:00Z",
  },
  {
    firstName: "Amit",
    lastName: "Kumar",
    email: "a.kumar@frpengineering.com",
    department: "Workshop / Field",
    roleIds: ["role-field-engineer"],
    roleNames: ["Field Engineer"],
    status: "active",
    lastLogin: "Oct 24, 07:40 AM",
    region: "Asia Pacific",
    createdAt: "2025-06-30T09:00:00Z",
  },
  {
    firstName: "Neha",
    lastName: "Singh",
    email: "n.singh@frpengineering.com",
    department: "Draftsmen",
    roleIds: ["role-support-specialist"],
    roleNames: ["Support Specialist"],
    status: "active",
    lastLogin: "Oct 21, 16:20 PM",
    region: "Asia Pacific",
    createdAt: "2025-07-11T09:00:00Z",
  },
  {
    firstName: "Michael",
    lastName: "Brown",
    email: "m.brown@frpengineering.com",
    department: "Project Managers",
    roleIds: ["role-operations-manager"],
    roleNames: ["Operations Manager"],
    status: "active",
    lastLogin: "Oct 20, 13:10 PM",
    region: "North America",
    createdAt: "2025-02-04T09:00:00Z",
  },
  {
    firstName: "Sarah",
    lastName: "Wilson",
    email: "s.wilson@frpengineering.com",
    department: "Admin / Accounts",
    roleIds: ["role-org-admin"],
    roleNames: ["Org Admin"],
    status: "active",
    lastLogin: "Oct 24, 08:55 AM",
    region: "Europe",
    createdAt: "2024-10-22T09:00:00Z",
  },
  {
    firstName: "James",
    lastName: "Holden",
    email: "j.holden@frpengineering.com",
    department: "Project Managers",
    roleIds: ["role-operations-manager"],
    roleNames: ["Operations Manager"],
    status: "active",
    lastLogin: "1 day ago",
    region: "North America",
    createdAt: "2026-08-01T09:00:00Z",
  },
  {
    firstName: "Naomi",
    lastName: "Nagata",
    email: "n.nagata@frpengineering.com",
    department: "Draftsmen",
    roleIds: ["role-support-specialist"],
    roleNames: ["Support Specialist"],
    status: "pending",
    lastLogin: null,
    region: "Asia Pacific",
    createdAt: "2026-07-29T09:00:00Z",
  },
  {
    firstName: "Amos",
    lastName: "Burton",
    email: "a.burton@frpengineering.com",
    department: "Workshop / Field",
    roleIds: ["role-field-engineer"],
    roleNames: ["Field Engineer"],
    status: "pending",
    lastLogin: null,
    region: "North America",
    createdAt: "2026-07-27T09:00:00Z",
  },
  {
    firstName: "Priya",
    lastName: "Iyer",
    email: "p.iyer@frpengineering.com",
    department: "Sales / QA",
    roleIds: ["role-support-specialist"],
    roleNames: ["Support Specialist"],
    status: "active",
    lastLogin: "Oct 19, 10:30 AM",
    region: "Asia Pacific",
    createdAt: "2025-09-16T09:00:00Z",
  },
  {
    firstName: "Oliver",
    lastName: "Novak",
    email: "o.novak@frpengineering.com",
    department: "Workshop / Field",
    roleIds: ["role-field-engineer"],
    roleNames: ["Field Engineer"],
    status: "active",
    lastLogin: "Oct 18, 09:00 AM",
    region: "Europe",
    createdAt: "2025-04-08T09:00:00Z",
  },
  {
    firstName: "Isabella",
    lastName: "Costa",
    email: "i.costa@frpengineering.com",
    department: "Draftsmen",
    roleIds: ["role-support-specialist"],
    roleNames: ["Support Specialist"],
    status: "inactive",
    lastLogin: "Jun 02, 12:00 PM",
    region: "Europe",
    createdAt: "2024-07-19T09:00:00Z",
  },
  {
    firstName: "Kenji",
    lastName: "Watanabe",
    email: "k.watanabe@frpengineering.com",
    department: "Workshop / Field",
    roleIds: ["role-field-engineer"],
    roleNames: ["Field Engineer"],
    status: "active",
    lastLogin: "Oct 17, 15:45 PM",
    region: "Asia Pacific",
    createdAt: "2025-01-27T09:00:00Z",
  },
  {
    firstName: "Grace",
    lastName: "Okafor",
    email: "g.okafor@frpengineering.com",
    department: "Project Managers",
    roleIds: ["role-operations-manager"],
    roleNames: ["Operations Manager"],
    status: "active",
    lastLogin: "Oct 16, 11:20 AM",
    region: "Europe",
    createdAt: "2025-10-10T09:00:00Z",
  },
  {
    firstName: "Liam",
    lastName: "Fraser",
    email: "l.fraser@frpengineering.com",
    department: "Workshop / Field",
    roleIds: ["role-field-engineer"],
    roleNames: ["Field Engineer"],
    status: "active",
    lastLogin: "Oct 15, 07:30 AM",
    region: "North America",
    createdAt: "2025-06-05T09:00:00Z",
  },
  {
    firstName: "Fatima",
    lastName: "Haidari",
    email: "f.haidari@frpengineering.com",
    department: "Sales / QA",
    roleIds: ["role-support-specialist"],
    roleNames: ["Support Specialist"],
    status: "active",
    lastLogin: "Oct 14, 14:00 PM",
    region: "Europe",
    createdAt: "2025-09-01T09:00:00Z",
  },
  {
    firstName: "David",
    lastName: "Kim",
    email: "d.kim@frpengineering.com",
    department: "Admin / Accounts",
    roleIds: ["role-org-admin"],
    roleNames: ["Org Admin"],
    status: "active",
    lastLogin: "Oct 13, 09:10 AM",
    region: "Asia Pacific",
    createdAt: "2024-11-30T09:00:00Z",
  },
  {
    firstName: "Chloe",
    lastName: "Bennett",
    email: "c.bennett@frpengineering.com",
    department: "Workshop / Field",
    roleIds: ["role-field-engineer"],
    roleNames: ["Field Engineer"],
    status: "active",
    lastLogin: "Oct 12, 16:50 PM",
    region: "North America",
    createdAt: "2025-05-16T09:00:00Z",
  },
  {
    firstName: "Yusuf",
    lastName: "Demir",
    email: "y.demir@frpengineering.com",
    department: "Workshop / Field",
    roleIds: ["role-field-engineer"],
    roleNames: ["Field Engineer"],
    status: "inactive",
    lastLogin: "Mar 03, 10:00 AM",
    region: "Europe",
    createdAt: "2024-05-21T09:00:00Z",
  },
  {
    firstName: "Emma",
    lastName: "Larsen",
    email: "e.larsen@frpengineering.com",
    department: "Sales / QA",
    roleIds: ["role-guest-viewer"],
    roleNames: ["Guest Viewer"],
    status: "pending",
    lastLogin: null,
    region: "Europe",
    createdAt: "2026-07-20T09:00:00Z",
  },
];

export const USERS: AdminUser[] = SEEDS.map((seed, index) => ({
  id: `user-${index + 1}`,
  firstName: seed.firstName,
  lastName: seed.lastName,
  fullName: `${seed.firstName} ${seed.lastName}`,
  email: seed.email,
  department: seed.department,
  roleIds: seed.roleIds,
  roleNames: seed.roleNames,
  status: seed.status,
  lastLogin: seed.lastLogin,
  failedAttempts: seed.failedAttempts,
  avatarInitials: initials(seed.firstName, seed.lastName),
  avatarColor: colorFor(index),
  region: seed.region,
  createdAt: seed.createdAt,
}));

export const DEPARTMENTS = [
  "Workshop / Field",
  "Project Managers",
  "Draftsmen",
  "Admin / Accounts",
  "Sales / QA",
] as const;
